#!/usr/bin/env python3

class Foreground:
    Green = "\033[38;5;46m"
    Yellow = "\033[38;5;226m"
    Red = "\033[38;5;196m"

class Background:
    Grey = "\033[48;5;248m"
    Yellow = "\033[48;5;226m"

Reset = "\033[0;0m"

print(f"{Background.Grey}{Foreground.Red}Red text on grey background{Reset}")
