#!/usr/bin/env python3

class Foreground:
    Green = "\033[38;5;46m"
    Yellow = "\033[38;5;226m"
    Red = "\033[38;5;196m"

class Background:
    Grey = "\033[48;5;248m"
    Yellow = "\033[48;5;226m"

Reset = "\033[0;0m"

def Position(x, y):
    return f"\033[{x};{y}H"

for i in range(20):
    print(f"{Position(i+2, i+1)}{Background.Grey}{Foreground.Red}{i}{Reset}")
