#!/usr/bin/env python3

import time
import os

class Foreground:
    Green = "\033[38;5;46m"
    Yellow = "\033[38;5;226m"
    Red = "\033[38;5;196m"

class Background:
    Grey = "\033[48;5;248m"
    Yellow = "\033[48;5;226m"

Reset = "\033[0;0m"

def Position(x, y):
    return f"\033[{x};{y}H"

while True:
    print(f"{Position(5, 15)}{Background.Yellow}  ")
    time.sleep(0.5)
    print(f"{Position(5, 15)}{Reset}  ")
    time.sleep(0.5)

